emplist1 = list()
print(emplist1)
emplist1.append(9)
print(emplist1)
emplist1.append(10)
print(emplist1)
emplist1.extend('a')
emplist1.extend('b')
emplist1.extend('c')
print(emplist1)
emplist2 = []
print(emplist2)
emplist2.extend('a')
emplist2.extend('b')
emplist2.extend('c')
print(emplist2)
e = emplist2.pop()
print(emplist2)
print(e)
